jdbc.driverClassName = com.mysql.jdbc.Driver
jdbc.url = jdbc:mysql://54.205.138.77:3306/infrasuppengg
jdbc.username = root
#jdbc.password = infadmin
jdbc.password =harsha

#Mail Settings
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
